<?php

/**
 * Debugger bluescreen template.
 *
 * This file is part of the Nette Framework (http://nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 *
 * @param      array     $exception
 * @param      array     $panels
 * @return     void
 */

namespace SlimBluescreen;

use SlimBluescreen;

$title = ($exception instanceof \ErrorException && isset(static::$errorTypes[$exception->getCode()])) ? static::$errorTypes[$exception->getCode()] : get_class($exception);

$counter = 0;

?><!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="robots" content="noindex">

	<title><?php
		echo htmlspecialchars($title);
		$ex = $exception;
		echo ' ' . htmlspecialchars($ex->getMessage() . ($ex->getCode() ? ' #' . $ex->getCode() : ''), ENT_IGNORE);
		while ($ex = $ex->getPrevious())
			echo htmlspecialchars('; caused by ' . get_class($ex) . ' ' . $ex->getMessage() . ($ex->getCode() ? ' #' . $ex->getCode() : ''), ENT_IGNORE);
	?></title>

	<style type="text/css" class="nette-debug"><?php require __DIR__ . '/bluescreen.css' ?></style>
</head>


<body>
<script>document.body.className+=' js'</script>
<div id="netteBluescreen">
	<a id="netteBluescreenIcon" href="#" class="nette-toggle"></a>
	<div>
		<div id="netteBluescreenError" class="panel">
			<h1><?php echo htmlspecialchars($title), ($exception->getCode() ? ' #' . $exception->getCode() : '') ?></h1>

			<p><?php echo htmlspecialchars($exception->getMessage(), ENT_IGNORE) ?> <a href="http://www.google.com/search?q=<?php echo urlencode($title . ' ' . preg_replace('#\'.*\'|".*"#Us', '', $exception->getMessage())) ?>" id="netteBsSearch">search&#x25ba;</a></p>
		</div>

		<?php if ($prev = $exception->getPrevious()): ?>
		<div class="caused">
			<a href="#netteCaused">Caused by <?php echo get_class($prev) ?></a>
		</div>
		<?php endif ?>


		<?php $ex = $exception; $level = 0; ?>
		<?php do { ?>

			<?php if ($level++): ?>
			<div class="panel"<?php if ($level === 2) echo ' id="netteCaused"' ?>>
			<h2><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle<?php echo ($collapsed = $level > 2) ? '-collapsed' : '' ?>">Caused by</a></h2>

			<div id="netteBsPnl<?php echo $counter ?>" class="<?php echo $collapsed ? 'nette-collapsed ' : '' ?>inner">
				<div class="panel">
					<h1><?php echo htmlspecialchars(get_class($ex) . ($ex->getCode() ? ' #' . $ex->getCode() : '')) ?></h1>

					<p><b><?php echo htmlspecialchars($ex->getMessage(), ENT_IGNORE) ?></b></p>
				</div>
			<?php endif ?>


			<?php foreach ($panels as $panel): ?>
			<?php $panel = call_user_func($panel, $ex); if (empty($panel['tab']) || empty($panel['panel'])) continue; ?>
			<?php if (!empty($panel['bottom'])) { continue; } ?>
			<div class="panel">
				<h2><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle"><?php echo htmlSpecialChars($panel['tab']) ?></a></h2>

				<div id="netteBsPnl<?php echo $counter ?>" class="inner">
				<?php echo $panel['panel'] ?>
			</div></div>
			<?php endforeach ?>


			<?php $stack = $ex->getTrace(); $expanded = NULL ?>
			<?php if ((!$exception instanceof \ErrorException || in_array($exception->getSeverity(), array(E_USER_NOTICE, E_USER_WARNING, E_USER_DEPRECATED))) && $this->isCollapsed($ex->getFile())) {
				foreach ($stack as $key => $row) {
					if (isset($row['file']) && !$this->isCollapsed($row['file'])) { $expanded = $key; break; }
				}
			} ?>

			<div class="panel">
			<h2><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle<?php echo ($collapsed = $expanded !== NULL) ? '-collapsed' : '' ?>">Source file</a></h2>

			<div id="netteBsPnl<?php echo $counter ?>" class="<?php echo $collapsed ? 'nette-collapsed ' : '' ?>inner">
				<p><b>File:</b> <?php echo static::editorLink($ex->getFile(), $ex->getLine()) ?></p>
				<?php if (is_file($ex->getFile())): ?><?php echo self::highlightFile($ex->getFile(), $ex->getLine(), 15, isset($ex->context) ? $ex->context : NULL) ?><?php endif ?>
			</div></div>


			<?php if (isset($stack[0]['class']) && $stack[0]['class'] === 'Slim\Slim' && $stack[0]['function'] === 'handleErrors') unset($stack[0]) ?>
			<?php if ($stack): ?>
			<div class="panel">
				<h2><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle">Call stack</a></h2>

				<div id="netteBsPnl<?php echo $counter ?>" class="inner">
				<ol>
					<?php foreach ($stack as $key => $row): ?>
					<li><p>

					<?php if (isset($row['file']) && is_file($row['file'])): ?>
						<?php echo static::editorLink($row['file'], $row['line']) ?>
					<?php else: ?>
						<i>inner-code</i><?php if (isset($row['line'])) echo ':', $row['line'] ?>
					<?php endif ?>

					<?php if (isset($row['file']) && is_file($row['file'])): ?><a href="#netteBsSrc<?php echo "$level-$key" ?>" class="nette-toggle-collapsed">source</a>&nbsp; <?php endif ?>

					<?php if (isset($row['object'])) echo "<a href='#netteBsObj$level-$key' class='nette-toggle-collapsed'>" ?>
					<?php if (isset($row['class'])) echo htmlspecialchars($row['class'] . $row['type']) ?>
					<?php if (isset($row['object'])) echo '</a>' ?>
					<?php echo htmlspecialchars($row['function']) ?>

					(<?php if (!empty($row['args'])): ?><a href="#netteBsArgs<?php echo "$level-$key" ?>" class="nette-toggle-collapsed">arguments</a><?php endif ?>)
					</p>

					<?php if (isset($row['file']) && is_file($row['file'])): ?>
						<div <?php if ($expanded !== $key) echo 'class="nette-collapsed"'; ?> id="netteBsSrc<?php echo "$level-$key" ?>"><?php echo self::highlightFile($row['file'], $row['line']) ?></div>
					<?php endif ?>

					<?php if (isset($row['object'])): ?>
						<div class="nette-collapsed outer" id="netteBsObj<?php echo "$level-$key" ?>"><?php echo static::pTopToHtml($row['object']); ?></div>
					<?php endif ?>

					<?php if (!empty($row['args'])): ?>
						<div class="nette-collapsed outer" id="netteBsArgs<?php echo "$level-$key" ?>">
						<table>
						<?php
						try {
							$r = isset($row['class']) ? new \ReflectionMethod($row['class'], $row['function']) : new \ReflectionFunction($row['function']);
							$params = $r->getParameters();
						} catch (\Exception $e) {
							$params = array();
						}
						foreach ($row['args'] as $k => $v) {
							echo '<tr><th>', htmlspecialchars(isset($params[$k]) ? '$' . $params[$k]->name : "#$k"), '</th><td>';
							echo Dumper::toHtml($v);
							echo "</td></tr>\n";
						}
						?>
						</table>
						</div>
					<?php endif ?>
					</li>
					<?php endforeach ?>
				</ol>
			</div></div>
			<?php endif ?>


			<?php if (isset($ex->context) && is_array($ex->context)):?>
			<div class="panel">
			<h2><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle-collapsed">Variables</a></h2>

			<div id="netteBsPnl<?php echo $counter ?>" class="nette-collapsed inner">
			<div class="outer">
			<table>
			<?php
			foreach ($ex->context as $k => $v) {
					echo '<tr><th>$', htmlspecialchars($k), '</th><td>', Dumper::toHtml($v), "</td></tr>\n";
			}
			?>
			</table>
			</div>
			</div></div>
			<?php endif ?>

		<?php } while ($ex = $ex->getPrevious()); ?>
		<?php while (--$level) echo '</div></div>' ?>


		<?php $bottomPanels = array() ?>
		<?php foreach ($panels as $panel): ?>
		<?php $panel = call_user_func($panel, NULL); if (empty($panel['tab']) || empty($panel['panel'])) continue; ?>
		<?php if (!empty($panel['bottom'])) { $bottomPanels[] = $panel; continue; } ?>
		<div class="panel">
			<h2><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle-collapsed"><?php echo htmlSpecialChars($panel['tab']) ?></a></h2>

			<div id="netteBsPnl<?php echo $counter ?>" class="nette-collapsed inner">
			<?php echo $panel['panel'] ?>
		</div></div>
		<?php endforeach ?>

		<div class="panel">
		<h2><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle-collapsed">Environment</a></h2>

		<div id="netteBsPnl<?php echo $counter ?>" class="nette-collapsed inner">
			<h3><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle">$_SERVER</a></h3>
			<div id="netteBsPnl<?php echo $counter ?>" class="outer">
			<table>
			<?php
			foreach ($_SERVER as $k => $v) echo '<tr><th>', htmlspecialchars($k), '</th><td>', Dumper::toHtml($v), "</td></tr>\n";
			?>
			</table>
			</div>


			<h3><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle">$_SESSION</a></h3>
			<div id="netteBsPnl<?php echo $counter ?>" class="outer">
			<?php if (empty($_SESSION)):?>
			<p><i>empty</i></p>
			<?php else: ?>
			<table>
			<?php
			foreach ($_SESSION as $k => $v) echo '<tr><th>', htmlspecialchars($k), '</th><td>', $k === '__NF' ? '<i>Nette Session</i>' : Dumper::toHtml($v), "</td></tr>\n";
			?>
			</table>
			<?php endif ?>
			</div>


			<?php if (!empty($_SESSION['__NF']['DATA'])):?>
			<h3><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle">Nette Session</a></h3>
			<div id="netteBsPnl<?php echo $counter ?>" class="outer">
			<table>
			<?php
			foreach ($_SESSION['__NF']['DATA'] as $k => $v) echo '<tr><th>', htmlspecialchars($k), '</th><td>', Dumper::toHtml($v), "</td></tr>\n";
			?>
			</table>
			</div>
			<?php endif ?>


			<?php
			$list = get_defined_constants(TRUE);
			if (!empty($list['user'])):?>
			<h3><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle-collapsed">Constants</a></h3>
			<div id="netteBsPnl<?php echo $counter ?>" class="outer nette-collapsed">
			<table>
			<?php
			foreach ($list['user'] as $k => $v) {
				echo '<tr><th>', htmlspecialchars($k), '</th>';
				echo '<td>', Dumper::toHtml($v), "</td></tr>\n";
			}
			?>
			</table>
			</div>
			<?php endif ?>


			<h3><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle-collapsed">Included files</a> (<?php echo count(get_included_files()) ?>)</h3>
			<div id="netteBsPnl<?php echo $counter ?>" class="outer nette-collapsed">
			<table>
			<?php
			foreach (get_included_files() as $v) {
				echo '<tr><td>', htmlspecialchars($v, ENT_IGNORE), "</td></tr>\n";
			}
			?>
			</table>
			</div>


			<h3><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle-collapsed">Configuration options</a></h3>
			<div id="netteBsPnl<?php echo $counter ?>" class="outer nette-collapsed">
			<?php ob_start(); @phpinfo(INFO_CONFIGURATION | INFO_MODULES); echo preg_replace('#^.+<body>|</body>.+\z#s', '', ob_get_clean()) ?>
			</div>
		</div></div>


		<div class="panel">
		<h2><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle-collapsed">HTTP request</a></h2>

		<div id="netteBsPnl<?php echo $counter ?>" class="nette-collapsed inner">
			<?php if (function_exists('apache_request_headers')): ?>
			<h3>Headers</h3>
			<div class="outer">
			<table>
			<?php
			foreach (apache_request_headers() as $k => $v) echo '<tr><th>', htmlspecialchars($k), '</th><td>', htmlspecialchars($v), "</td></tr>\n";
			?>
			</table>
			</div>
			<?php endif ?>


			<?php foreach (array('_GET', '_POST', '_COOKIE') as $name): ?>
			<h3>$<?php echo htmlspecialchars($name) ?></h3>
			<?php if (empty($GLOBALS[$name])):?>
			<p><i>empty</i></p>
			<?php else: ?>
			<div class="outer">
			<table>
			<?php
			foreach ($GLOBALS[$name] as $k => $v) echo '<tr><th>', htmlspecialchars($k), '</th><td>', Dumper::toHtml($v), "</td></tr>\n";
			?>
			</table>
			</div>
			<?php endif ?>
			<?php endforeach ?>
		</div></div>


		<div class="panel">
		<h2><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle-collapsed">HTTP response</a></h2>

		<div id="netteBsPnl<?php echo $counter ?>" class="nette-collapsed inner">
			<h3>Headers</h3>
			<?php if (headers_list()): ?>
			<pre><?php
			foreach (headers_list() as $s) echo htmlspecialchars($s, ENT_IGNORE), '<br>';
			?></pre>
			<?php else: ?>
			<p><i>no headers</i></p>
			<?php endif ?>
		</div></div>


		<?php foreach ($bottomPanels as $panel): ?>
		<div class="panel">
			<h2><a href="#netteBsPnl<?php echo ++$counter ?>" class="nette-toggle"><?php echo htmlSpecialChars($panel['tab']) ?></a></h2>

			<div id="netteBsPnl<?php echo $counter ?>" class="inner">
			<?php echo $panel['panel'] ?>
		</div></div>
		<?php endforeach ?>


		<ul>
			<li>Report generated at <?php echo @date('Y/m/d H:i:s', $this->time) ?></li>
			<?php if (preg_match('#^https?://#', $this->source)): ?>
				<li><a href="<?php echo htmlSpecialChars($this->source, ENT_IGNORE | ENT_QUOTES) ?>"><?php echo htmlSpecialChars($this->source, ENT_IGNORE) ?></a></li>
			<?php elseif ($this->source): ?>
				<li><?php echo htmlSpecialChars($this->source, ENT_IGNORE) ?></li>
			<?php endif ?>
			<li>PHP <?php echo htmlSpecialChars(PHP_VERSION) ?></li>
			<?php if (isset($_SERVER['SERVER_SOFTWARE'])): ?><li><?php echo htmlSpecialChars($_SERVER['SERVER_SOFTWARE']) ?></li><?php endif ?>
			<?php  if (class_exists('Slim\Slim')): ?><li><?php echo htmlSpecialChars('Slim Framework ' . \Slim\Slim::VERSION) ?></li><?php endif ?>
		</ul>
	</div>
</div>

<script type="text/javascript"><?php require __DIR__ . '/bluescreen.js' ?></script>
</body>
</html>
